services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: utopia_frontend
    ports:
      - "3000:3000"
    environment:
      WATCHPACK_POLLING: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - utopia-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: utopia_backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/code
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - utopia-network

  db:
    image: mysql:8.0
    container_name: utopia_db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=utopia_dev
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - utopia-network

networks:
  utopia-network:
    driver: bridge

volumes:
  node_modules:
  db_data:
